#!/usr/bin/env bash
set -e

# Install coursier
# curl -fLo cs https://github.com/coursier/coursier/releases/download/v2.0.3/cs-x86_64-pc-linux
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier

SCALA_VERSION=2.13.3
ALMOND_VERSION=0.10.9

# Install almond for Scala 2.12
./coursier launch --fork "almond:$ALMOND_VERSION" --scala $SCALA_VERSION -- \
  --install \
  --id scala213 \
  --display-name "Scala (2.13)" \
  --env "JAVA_OPTS=-XX:MaxRAMPercentage=80.0" \
  --variable-inspector \
  </dev/null 2>&1 | grep -v '^Download'

#
# Install IJava Kernel
#

curl -Lo ijava-1.3.0.zip https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip
mkdir ijava
cd ijava
unzip ../ijava-1.3.0.zip
python3 install.py --user

jupyter contrib nbextension install --user
# jupyter nbextension enable --py widgetsnbextension

# Set indentation to two spaces
JUPYTER_CONFIG_DIR=$(jupyter --config-dir)

# Classic notebook
mkdir -p $JUPYTER_CONFIG_DIR/nbconfig/
cat > $JUPYTER_CONFIG_DIR/nbconfig/notebook.json <<- EOF
{
  "Notebook": {
    "Header": true
  },
  "load_extensions": {
    "nbextensions_configurator/config_menu/main": true,
    "contrib_nbextensions_help_item/main": true,
    "exercise2/main": true
  }
}
EOF
